AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  line-bot-demo-chap

Globals:
  Function:
    Timeout: 3
    MemorySize: 128
Parameters: 
  LineKey: 
    Type: String
    Default: youForgotTheKey
    Description: line access token

Resources:
  LineReplyFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: lineBot/
      Handler: app.answer
      Runtime: python3.8
      Environment:
        Variables:
          ACCESS_TOKEN: !Ref LineKey
      Events:
        LineReply:
          Type: Api 
          Properties:
            Path: /linereply
            Method: post

Outputs:
  ChatEndpoint:
    Description: "api endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/linereply/"
